apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        image: kranurag7/simplewhale:latest
        imagePullPolicy: Always
        name: server
        ports:
        - containerPort: 8080
      terminationGracePeriodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort
